version: "3.9"

services:
  redis:
    image: redis:7.0
    ports:
      - '6379:6379'

  sidekiq_worker:
    build:
      context: .
    command: bundle exec rake worker
    links:
      - redis
    env_file:
      - .env
